version: '3.9'

services:
  cache:
    image: redis/redis-stack
    container_name: redis_db
    restart: always
    ports:
      - '6379:6379'
      - '10001:8001'
    command: redis-server --save 20 1 --loglevel warning
    volumes: 
      - cache_volume:/data

volumes:
  cache_volume:
    driver: local
networks:
  backend_nw:
